spring:
  config:
    activate:
      on-profile: dev
  profiles:
    include:
      - aws
      - credentials
  autoconfigure:
    exclude: org.springframework.cloud.aws.autoconfigure.context.ContextStackAutoConfiguration
  datasource:
    url: {MYSQL_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: {MYSQL_USERNAME}
    password: {MYSQL_PASSWORD}
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    database: mysql
  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
    host: smtp.gmail.com
    username: {MAIL_HOST}
    password: {MAIL_PASSWORD}
    port: {MAIL_PORT}
  redis:
    host: {REDIS_URL}
    port: {REDIS_PORT}

  main:
    allow-circular-references: true
  jwt:
    secret: {JWT_SECRET}
    jwtExpirationMs: {JWT_EXPI}
  mvc:
    path match:
      matching-strategy: ant_path_matcher
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 10MB
server:
  tomcat:
    uri-encoding: UTF-8
cloud:
  aws:
    credentials:
      accessKey: {AWS_ACCESSKEY}
      secretKey: {AWS_SECRETKEY}
    s3:
      bucket: {BUCKET_NAME}
      dir: /test
      mock:
        port: 3306
    region:
      static: {AWS_REGION}
      auto: false
      use-default-aws-region-chain: true
    stack:
      auto: false
logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG
    com:
      amazonaws:
        internal:
          InstanceMetadataServiceResourceFetcher: error
        util:
          EC2MetadataUtils: error
